# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0006_auto_20180108_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('count', models.IntegerField()),
                ('good', models.ManyToManyField(related_name='goods_in_basket', to='internet_shop.Good')),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='goods',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
