# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0007_auto_20180113_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitems',
            name='good',
        ),
        migrations.AddField(
            model_name='basketitems',
            name='good',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='goods_in_basket', to='internet_shop.Good'),
            preserve_default=False,
        ),
    ]
