# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0009_auto_20180113_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbasketitems',
            old_name='count',
            new_name='count_of',
        )
    ]
