# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0013_auto_20180113_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='good_color', to='internet_shop.Colors'),
        ),
    ]
