# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0014_auto_20180113_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasketitems',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='color_in_basket', to='internet_shop.Colors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbasketitems',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='size_in_basket', to='internet_shop.Sizes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='good_sizes', to='internet_shop.Sizes'),
        ),
    ]
