# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0015_auto_20180113_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='good_images'),
        ),
    ]
