# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0018_auto_20180216_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='color',
        ),
        migrations.RemoveField(
            model_name='good',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='userbasketitems',
            name='color',
        ),
        migrations.RemoveField(
            model_name='userbasketitems',
            name='size',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
