# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0019_auto_20180216_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasketitems',
            name='summ',
            field=models.IntegerField(default=0),
        ),
    ]
