# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0020_userbasketitems_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
