# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0021_auto_20180216_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=1000)),
                ('user_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='internet_shop.UserBasketItems')),
            ],
        ),
    ]
