# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('internet_shop', '0022_readyorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readyorder',
            name='user_basket',
        ),
        migrations.AddField(
            model_name='readyorder',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ede2f454-c403-48f1-9e02-a515f18a7ec8'), editable=False),
        ),
        migrations.AlterField(
            model_name='userbasketitems',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c7d15395-0c5b-4bb7-bab5-d72b929814ee'), editable=False),
        ),
    ]
